<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sedes [
<!ELEMENT sedes (francia, italia, dinamarca)>
<!ELEMENT francia (ciudad+)>
<!ELEMENT italia (ciudad+)>
<!ELEMENT dinamarca (ciudad+)>
<!ELEMENT ciudad (#PCDATA)>
]>
<sedes>
<francia>
<ciudad>Paris</ciudad>
<ciudad>Nantes</ciudad>
</francia>
<italia>
<ciudad>Roma</ciudad>
<ciudad>Florencia</ciudad>
<ciudad>Venecia</ciudad>
</italia>
<dinamarca>
<ciudad>Copenhague</ciudad>
</dinamarca>
</sedes>