<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulos [
    <!ELEMENT articulos (articulo*)>
    <!ELEMENT articulo ((codigo | id), nombre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT id (#PCDATA)>


]>
<articulos>
    <articulo>
        <codigo>003A</codigo>
        <nombre>Tuerca</nombre>
    </articulo>
    <articulo>
        <id>8</id>
        <nombre>Tornillo 6</nombre>
    </articulo>
</articulos>