=== AntonioXam/XML/DTD/prueba2/marcadores.dtd
<!ELEMENT marcadores (marcador*)>
    <!ELEMENT marcador (nombre, descripcion, url)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT url (#PCDATA)>

=== AntonioXam/XML/DTD/prueba2/marcadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores SYSTEM "marcadores.dtd">

<marcadores>
    <marcador>
        <nombre>W3schools</nombre>
        <descripcion>Tutoriales web online</descripcion>
        <url>http://www.w3schools.com/</url>
    </marcador>
    <marcador>
        <nombre>Wikipedia</nombre>
        <descripcion>La enciclopedia libre</descripcion>
        <url>http://www.wikipedia.org/</url>
    </marcador>
    <marcador>
        <nombre>W3C</nombre>
        <descripcion>Word Wide Web Consortium</descripcion>
        <url>http://www.w3.org/</url>
    </marcador>
</marcadores>
